[
  {
    "url": "https://api.github.com/repos/quarnster/SublimeClang/issues/comments/14652472",
    "html_url": "https://github.com/quarnster/SublimeClang/issues/217#issuecomment-14652472",
    "issue_url": "https://api.github.com/repos/quarnster/SublimeClang/issues/217",
    "id": 14652472,
    "user": {
      "login": "sebastient",
      "id": 223432,
      "avatar_url": "https://secure.gravatar.com/avatar/e71d9a34faf00555e41adc667e4cd4e1?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png",
      "gravatar_id": "e71d9a34faf00555e41adc667e4cd4e1",
      "url": "https://api.github.com/users/sebastient",
      "html_url": "https://github.com/sebastient",
      "followers_url": "https://api.github.com/users/sebastient/followers",
      "following_url": "https://api.github.com/users/sebastient/following",
      "gists_url": "https://api.github.com/users/sebastient/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/sebastient/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/sebastient/subscriptions",
      "organizations_url": "https://api.github.com/users/sebastient/orgs",
      "repos_url": "https://api.github.com/users/sebastient/repos",
      "events_url": "https://api.github.com/users/sebastient/events{/privacy}",
      "received_events_url": "https://api.github.com/users/sebastient/received_events",
      "type": "User"
    },
    "created_at": "2013-03-08T23:37:20Z",
    "updated_at": "2013-03-08T23:37:20Z",
    "body": "Looking at the console I'm seeing this error when SublimeClang loads.\r\n\r\nTraceback (most recent call last):\r\n  File \"./sublime_plugin.py\", line 62, in reload_plugin\r\n  File \"./sublimeclang.py\", line 47, in <module>\r\n    import queue as Queue\r\nImportError: No module named queue\r\n"
  },
  {
    "url": "https://api.github.com/repos/quarnster/SublimeClang/issues/comments/14652905",
    "html_url": "https://github.com/quarnster/SublimeClang/issues/217#issuecomment-14652905",
    "issue_url": "https://api.github.com/repos/quarnster/SublimeClang/issues/217",
    "id": 14652905,
    "user": {
      "login": "sebastient",
      "id": 223432,
      "avatar_url": "https://secure.gravatar.com/avatar/e71d9a34faf00555e41adc667e4cd4e1?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png",
      "gravatar_id": "e71d9a34faf00555e41adc667e4cd4e1",
      "url": "https://api.github.com/users/sebastient",
      "html_url": "https://github.com/sebastient",
      "followers_url": "https://api.github.com/users/sebastient/followers",
      "following_url": "https://api.github.com/users/sebastient/following",
      "gists_url": "https://api.github.com/users/sebastient/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/sebastient/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/sebastient/subscriptions",
      "organizations_url": "https://api.github.com/users/sebastient/orgs",
      "repos_url": "https://api.github.com/users/sebastient/repos",
      "events_url": "https://api.github.com/users/sebastient/events{/privacy}",
      "received_events_url": "https://api.github.com/users/sebastient/received_events",
      "type": "User"
    },
    "created_at": "2013-03-08T23:50:04Z",
    "updated_at": "2013-03-08T23:50:04Z",
    "body": "I added a print for the ImportError that leads to trying the Python 3 naming convention and got (Failed to import:  No module named parsehelp.parsehelp).  Is there some extra work required to get this library working with SublimeClang?"
  },
  {
    "url": "https://api.github.com/repos/quarnster/SublimeClang/issues/comments/14658777",
    "html_url": "https://github.com/quarnster/SublimeClang/issues/217#issuecomment-14658777",
    "issue_url": "https://api.github.com/repos/quarnster/SublimeClang/issues/217",
    "id": 14658777,
    "user": {
      "login": "quarnster",
      "id": 1230389,
      "avatar_url": "https://secure.gravatar.com/avatar/10a89302c6736c988ce06d8a41c923c0?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png",
      "gravatar_id": "10a89302c6736c988ce06d8a41c923c0",
      "url": "https://api.github.com/users/quarnster",
      "html_url": "https://github.com/quarnster",
      "followers_url": "https://api.github.com/users/quarnster/followers",
      "following_url": "https://api.github.com/users/quarnster/following",
      "gists_url": "https://api.github.com/users/quarnster/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/quarnster/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/quarnster/subscriptions",
      "organizations_url": "https://api.github.com/users/quarnster/orgs",
      "repos_url": "https://api.github.com/users/quarnster/repos",
      "events_url": "https://api.github.com/users/quarnster/events{/privacy}",
      "received_events_url": "https://api.github.com/users/quarnster/received_events",
      "type": "User"
    },
    "created_at": "2013-03-09T06:10:04Z",
    "updated_at": "2013-03-09T06:10:04Z",
    "body": "Did you do a recursive submodule init? Did you build libcache?"
  }
]
