[
  {
    "url": "https://api.github.com/repos/quarnster/SublimeClang/issues/comments/4666970",
    "html_url": "https://github.com/quarnster/SublimeClang/issues/39#issuecomment-4666970",
    "issue_url": "https://api.github.com/repos/quarnster/SublimeClang/issues/39",
    "id": 4666970,
    "user": {
      "login": "quarnster",
      "id": 1230389,
      "avatar_url": "https://secure.gravatar.com/avatar/10a89302c6736c988ce06d8a41c923c0?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png",
      "gravatar_id": "10a89302c6736c988ce06d8a41c923c0",
      "url": "https://api.github.com/users/quarnster",
      "html_url": "https://github.com/quarnster",
      "followers_url": "https://api.github.com/users/quarnster/followers",
      "following_url": "https://api.github.com/users/quarnster/following",
      "gists_url": "https://api.github.com/users/quarnster/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/quarnster/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/quarnster/subscriptions",
      "organizations_url": "https://api.github.com/users/quarnster/orgs",
      "repos_url": "https://api.github.com/users/quarnster/repos",
      "events_url": "https://api.github.com/users/quarnster/events{/privacy}",
      "received_events_url": "https://api.github.com/users/quarnster/received_events",
      "type": "User"
    },
    "created_at": "2012-03-23T20:10:29Z",
    "updated_at": "2012-03-23T20:10:29Z",
    "body": "@notlion Could you please try now? There's still an issue when starting Sublime Text 2 and you had multiple windows with different projects in them opened. I don't think there's anything I can do about that. See the commit message for more details."
  },
  {
    "url": "https://api.github.com/repos/quarnster/SublimeClang/issues/comments/4667576",
    "html_url": "https://github.com/quarnster/SublimeClang/issues/39#issuecomment-4667576",
    "issue_url": "https://api.github.com/repos/quarnster/SublimeClang/issues/39",
    "id": 4667576,
    "user": {
      "login": "notlion",
      "id": 27721,
      "avatar_url": "https://secure.gravatar.com/avatar/ebe56818599c45146ff4e146c946eab4?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png",
      "gravatar_id": "ebe56818599c45146ff4e146c946eab4",
      "url": "https://api.github.com/users/notlion",
      "html_url": "https://github.com/notlion",
      "followers_url": "https://api.github.com/users/notlion/followers",
      "following_url": "https://api.github.com/users/notlion/following",
      "gists_url": "https://api.github.com/users/notlion/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/notlion/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/notlion/subscriptions",
      "organizations_url": "https://api.github.com/users/notlion/orgs",
      "repos_url": "https://api.github.com/users/notlion/repos",
      "events_url": "https://api.github.com/users/notlion/events{/privacy}",
      "received_events_url": "https://api.github.com/users/notlion/received_events",
      "type": "User"
    },
    "created_at": "2012-03-23T20:44:57Z",
    "updated_at": "2012-03-23T20:44:57Z",
    "body": "This seems to work! I tried quitting, and reopening a couple times combined with clearing the cache and reparsing and everything is still being found. Thanks for the quick fix and the awesome package!"
  }
]
